version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  ingestion-api:
    build: ./ingestion-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_healthy

  processing-svc:
    build: ./processing-svc
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CONSUMER_NAME: consumer-1
    depends_on:
      redis:
        condition: service_healthy


